cargo-features = ["edition"]

[package]
edition = '2018'
name = "matrix-rs"
version = "0.1.0"
authors = ["Nicolas Mémeint <nicolas.memeint@gmail.com>"]

[features]
impl_from = []

[dev-dependencies]
rand = "0.5"
criterion = "0.2"
quickcheck = "0.6"

[[bench]]
name = "bench"
harness = false
